const errorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_2FA_TOKEN: 'INVALID_2FA_TOKEN',
  TWO_FACTOR_NOT_SETUP: 'TWO_FACTOR_NOT_SETUP',
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_EXISTS: 'USER_EXISTS',
};

export default errorCodes;
